### ISSUE TITLE
[Feature Request] POSIX ls usage

### ISSUE THREAD

**Issue by AndreiSva** [andreyorst/kaktree#15]
Right now kaktree needs a bunch of non-POSIX ls command line options to work. It would be great to POSIX-fy the ls usage in order to enable the plugin to be used on busybox or BSD systems.

**Comment by andreyorst** [comment]
Hi, can you be more specific on which tools are non-posix? It requires Perl, and ls with posix keys.

**Comment by AndreiSva** [comment]
@andreyorst -B is not defined by POSIX

**Comment by andreyorst** [comment]
kaktree doesn't require it, and doesn't use it. It seems like a typo in
readme.

**Comment by andreyorst** [comment]
@AndreiSva I've fixed the typo :smile:. Are there any actual errors on BSD or busybox systems?

**Comment by AndreiSva** [comment]
`-b` is still not defined by POSIX and doesn't work on busybox ls or OpenBSD ls, couldn't test on other coreutils. You can see a list of all portable ls options [here](https://www.unix.com/man-page/posix/1posix/ls/).

**Comment by andreyorst** [comment]
hmm `-b` can be worked around, I guess non-graphic characters are rare in files, though this needs more testing.

**Comment by andreyorst** [comment]
Alternatively we could gather the directory list with Perl, but this would require some reimplementation of the `build_tree` subroutine
